name: Release

on:
  workflow_dispatch:
  release:
    types: [published]


jobs:
  package:
    name: Package Release
    runs-on: ubuntu-latest
    steps:
      - name: Get release version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: .
      - name: "Update plugin.json version to: ${{ env.VERSION }}"
        uses: jossef/action-set-json-field@v1
        with:
          file: plugin.json
          field: Version
          value: ${{ env.VERSION }}
      - name: Move Flox to plugin root
        run: |
          mv -r ./lib/flox . && rm -r ./lib/Flox-*dist-info
      - name: Package files
        run: |
          zip -r HA-Commander.zip . -x '*.git*' -x 'demo.gif' -x 'README.md' -x 'assets/*'
      - name: Publish
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: 'HA-Commander.zip'
          tag_name: "v${{VERSION}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
