name: Release

on:
  push:
    tags:
      - 'v*'


jobs:
  release:
    name: Package Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Update plugin.json version to: ${{ env.VERSION }}"
        uses: jossef/action-set-json-field@v1
        with:
          file: plugin.json
          field: Version
          value: ${{ env.VERSION }}
      - name: Get release version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Commit version change
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./plugin.json
          git commit -m "bumping versioning ${{ env.VERSION }}"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ github.token }}
      - name: Download dev build
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: "tags/dev"
          file: "${{github.event.repository.name}}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Unzip prelease
        run: |
          mkdir -p ./staging
          unzip -d ./staging "${{github.event.repository.name}}.zip"
          mv ./plugin.json ./staging
      - name: Zip release
        run: |
          cd ./staging
          zip -r "${{github.event.repository.name}}.zip" . -x '*.git*' -x 'demo.gif' -x 'README.md' -x 'assets/*'
      - name: Publish
        uses: "marvinpinto/action-automatic-releases@latest"
        if: success()
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "v${{ env.VERSION }}"
          files: |
            "${{github.event.repository.name}}.zip"
        - name: Remove dev build
          uses: dev-drprasad/delete-older-releases@v0.2.0
          with:
            delete_tag_pattern: dev
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

