name: Build & Release

on:
  workflow_dispatch:
  release:
    types: [unpublished]

env:
  PYTHON_VER: 3.6


jobs:
  build:
    name: Build Plugin
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VER }}
      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Windows')
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt -t ./lib
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: . # or path/to/artifact
  package:
    name: Package Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get release version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: .
      - name: "Update plugin.json version to: ${{ env.VERSION }}"
        uses: jossef/action-set-json-field@v1
        with:
          file: plugin.json
          field: Version
          value: ${{ env.VERSION }}
      - name: Move Flox to plugin root
        run: |
          mv ./lib/flox . && rm -r ./lib/Flox-*-info
      - name: Package files
        run: |
          zip -r "${{github.event.repository.name}}.zip" . -x '*.git*' -x 'demo.gif' -x 'README.md' -x 'assets/*'
      - name: Publish
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: "${{github.event.repository.name}}.zip"
          tag_name: "v${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
